export const lemlistObj = {
  currency: "Euro",
  freePlan: {
    name: "Free Plan",
    benefits: [
      "Export unlimited leads from LinkedIn with",
      "Email finder &verifier (up to 100 free emails per month, refilled weekly)",
      "Phone number & verifier (up to 25 free phone numbers per month, refilled weekly)",
      "450M+ leads database",
      "AI message writing",
      "Enrich your leads from the web and your CRM with lemlist Google Sheets Add-on",
    ],
    cost: 0,
    emailCapacity: 0,
  },
  emailStarter: {
    name: "Email Starter",
    benefits: [
      "Everything in Free plan",
      "Send unlimited campaigns",
      "Email finder and verifier (up to 100 free emails/mo, refilled monthly)",
      "Phone number finder (up to 25 free phone/mo, refilled monthly)",
      "Customizable email campaigns",
      "Personalized booking page",
      "In-app support by chat or email",
    ],
    cost: 32,
    emailCapacity: 1,
  },
  emailPro: {
    name: "Email Pro",
    benefits: [
      "Everything in Email Starter",
      "Email finder + verifier (up to 150 free emails/mo)",
      "Phone number finder (up to 38 free phone/mo)",
      "Email warm-up and deliverability booster",
      "CRM integrations (Hubspot, Pipedrive, Salesforce)",
      "Custom text & image variable personalization",
      "Inbox rotation",
      "Custom liquid syntax personalization",
      "API access & Zapier",
    ],
    cost: 55,
    emailCapacity: 3,
  },
  multichannelExpert: {
    name: "Multichannel Expert",
    benefits: [
      "Everything in Email Pro",
      "Email finder + verifier (up to 300 free emails/mo)",
      "Phone number finder (up to 75 free phone/mo)",
      "LinkedIn prospection (profile visit, invitation, message)",
      "LinkedIn voice notes",
      "Campaign A/B tests",
      "Cold calling prospection with Aircall",
      "Advanced campaign conditions",
      "Custom landing page",
      "Premium support chat",
    ],
    cost: 79,
    emailCapacity: 5,
  },
  outreachScale: {
    name: "Outreach Scale",
    benefits: [
      "Everything in Multichannel Expert",
      "Email finder + verifier (up to 500 free emails/mo)",
      "Phone number finder (up to 125 free phone/mo)",
      "Personalized (1:1) Onboarding",
      "Dedicated account manager(5+ seats)",
      "Custom contracts (10+ seats)",
    ],
    cost: 129,
    emailCapacity: 15,
  },
};
